config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  
  # get 'home/index'
  get 'home/about'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :content, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to  "Blog App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <%= link_to  "About Me", home_about_path, class:"nav-link" %>
            </li>

            <% if user_signed_in? %>

            <li class="nav-item">
                <%= link_to  "New Post", new_post_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
            </li>

            <% else %>

            <li class="nav-item">
                <%= link_to  "Sign In", new_user_session_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "Sign Up", new_user_registration_path, class:"nav-link" %>
            </li>

            <% end %>

        </ul>
        <!--
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        -->
    </div>
</nav>

app/views/home/about.html.erb
<div class="card">
    <div class="card-header">
        <h4>About me</h4>
    </div>
    <div class="card-body">
        <p class="card-text">I'm <strong>Kostas</strong>, a developer residing in Athens, Greece.
            I created this web app to practice on Ruby on Rails and Bootstrap.</p>
        <p class="card-text">I have to say both are <strong>great</strong> tools i expect to use alot in future projects.</p>
        <p class="card-text">This project makes use of devise gem for user management and a Rails CRUD scaffold for the blog posts.</p>
    </div>
</div>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>This is my first Rails page</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Blog App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'home/header' %>
    <div class="container">
        <br />
        <% if notice %>
        <%=render 'layouts/alerts'%>
        <% end %>

        <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
<% if post.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
        <% post.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field form-group">
    <% form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
</div>

<div class="field form-group">
    <% form.label :author %>
    <%= form.text_field :author, class:"form-control", placeholder:"Author" %>
</div>

<div class="field form-group">
    <% form.label :content %>
    <%= form.text_field :content, class:"form-control", placeholder:"Content" %>
</div>

<div class="field form-group">
    <% form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"E-Mail" %>
</div>
<br />
<div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<br />
<%= render 'form', post: @post %>
<br />
<%= link_to 'Show', @post ,class:"btn btn-dark"%>
<%= link_to 'Back', posts_path, class:"btn btn-dark" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-hover table-bordered table-striped">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Content</th>
            <th>Email</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td><%=link_to post.title, post%></td>
            <td><%= post.author %></td>
            <td><%= post.content %></td>
            <td><%= post.email %></td>
            <td><%= link_to 'Edit', edit_post_path(post), class:"btn btn-outline-secondary"%></td>
            <td><%= link_to 'Destroy', post, class:"btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class:"btn btn-secondary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<br />
<%= render 'form', post: @post %>
<br />
<%= link_to 'Back', posts_path, class:"btn btn-dark" %>

app/views/posts/show.html.erb
<div class="jumbotron">
    <h1 class="display-4"><%= @post.title %></h1>
    <p class="lead"><%= @post.content %></p>
    <hr class="my-4">
    <p><%= @post.author %> | <%= @post.email %></p>
    <br /><br />
    <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-secondary" %>
    <%= link_to 'Back', posts_path, class:"btn btn-secondary" %>
</div>